version: "3.3"

services:
  db:
    image: mysql:8.0
    container_name: sysarch_mysql
    restart: unless-stopped
    tty: true
    volumes:
      - sysarch_db:/var/lib/mysql/
      #- ./dumps/schema-migration.sql:/docker-entrypoint-initdb.d/based.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - sysarch

  frontend:
    build:
      context: ./docker/dev/frontend
      dockerfile: Dockerfile
    user: node
    image: sysarch_node:0.1
    command: bash -c "npm install && npm run dev"
    restart: unless-stopped
    container_name: sysarch_frontend
    working_dir: /app/sysarch
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./src/sitio/frontend:/app
    networks:
      - sysarch

  nginx:
    image: nginx:latest
    container_name: sysarch_reverso
    restart: unless-stopped
    ports:
      - "${PORT_WEB}:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sysarch
    depends_on:
      - frontend

networks:
  sysarch:
    driver: bridge

volumes:
  sysarch_db: